blank_issues_enabled: false
contact_links:
  - name: Klipper Community Forum
    url: https://community.klipper3d.org/
    about: Forum dedicated to Klipper. Start here.
  - name: Klipper Discord Chat
    url: https://discord.klipper3d.org/
    about: Klipper community real-time chat server
  - name: Create a Klipper github issue
    url: issues/new
    about: Create a github issue
