# Enable the github stale issue bot tracker
name: "Add comment to issues marked invalid"
on:
  issues:
      types: [labeled]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.payload.label.name != "Invalid")
              return;
            msg = "Unfortunately, it appears the directions at:\n"
                + "  https://www.klipper3d.org/Contact.html\n"
                + "were not followed for this issue.\n"
                + "\n"
                + "We choose to use github as a tool for communication between"
                + " people working on improving Klipper. We choose not to use"
                + " github to help diagnose problems with a user's printer."
                + " We choose not to use github to answer user questions. We"
                + " choose not to use github as a place to make requests.\n"
                + "\n"
                + "In the future, please follow the directions at:\n"
                + "  https://www.klipper3d.org/Contact.html\n"
                + "This ticket will be automatically closed.\n"
                + "\n"
                + "Best regards,\n"
                + "~ Your friendly GitIssueBot\n"
                + "\n"
                + "PS: I'm just an automated script, not a human being.";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
