name: Lock Closed Issues
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
jobs:
  lock:
    name: Lock Closed Issues
    runs-on: ubuntu-latest
    steps:
    - uses: dessant/lock-threads@v3
      with:
        process-only: 'issues'
        issue-inactive-days: '30'
        issue-lock-reason: ''
