# Close and warn on tickets that have become stale
name: "Close stale tickets"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  # Mark unassigned PRs that are idle for 2 weeks
  mark_reviewer_needed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const create_check = new Date("2022-03-01T00:00:00Z").getTime();
            const expireMillis = 1000 * 60 * 60 * 24 * 14;
            const curtime = new Date().getTime();
            for await (const pr of github.paginate.iterator(
                       github.rest.pulls.listForRepo,
                       {
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                       })) {
              const createtime = new Date(pr.created_at).getTime();
              if (createtime < create_check)
                continue;
              const updatetime = new Date(pr.updated_at).getTime();
              if (curtime < updatetime + expireMillis)
                continue;
              console.log("dump context");
              console.log(pr);
              continue;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['reviewer needed']
              });
            }
