# Close and warn on tickets that have become stale
name: "Close stale tickets"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  # Mark unassigned PRs that are idle for 2 weeks
  mark_reviewer_needed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            const create_check = new Date("2022-03-01T00:00:00Z").getTime();
            const expireMillis = 1000 * 60 * 60 * 24 * 14;
            const curtime = new Date().getTime();
            const prs = await github.pulls.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'reviewer needed',
              assignee: 'none',
              per_page: 100,
              page: 1
            });
            for (const pr of prs.data.values()) {
              const createtime = new Date(pr.created_at).getTime();
              if (createtime < create_check)
                continue;
              const updatetime = new Date(pr.updated_at).getTime();
              if (curtime < updatetime + expireMillis)
                continue;
              console.log("dump context");
              console.log(pr);
              if (pr.labels.length > 0)
                continue;
              if (pr.assignees.length > 0)
                continue;
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['reviewer needed']
              });
            }
